# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
  - likhonsheikhcodes

ko_fi: likhonsheikh # Replace with your Ko-fi username

custom:
  - 'https://t.me/likhonsheikhcodes' # Replace with custom sponsorship URLs
  - 'mailto:likhonsheikhcodes@gmail.com'

# Uncomment the following lines if you set up these platforms in the future:
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with your Liberapay username
# issuehunt: # Replace with your IssueHunt username
# otechie: # Replace with your Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
